name: Build

on:
  push:
    branches:
      - "main"
    paths:
      - "**/*.cs"
  pull_request:
    branches:
      - "**"
    paths:
      - "Source/**"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.100-rc.2.21505.57"

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release
